name: keep-repo-alive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */50 * *' # every 50 days

permissions:
  contents: write
  
jobs:
  add_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ___RUN___
        run: |
          git config user.name  github-action
          git config user.email github-action@github.com
          
          date > keepalive.txt
          git commit -am 'Autocommit to keep repo in active state'
          git push
